CREATE DATABASE CVDatabase

USE CVDatabase

CREATE TABLE Skills(
Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY NOT NULL,
Name varchar(100) NOT NULL
)
CREATE TABLE Users(
Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY NOT NULL,
Username varchar(100) NOT NULL UNIQUE,
Email varchar(100) NOT NULL UNIQUE,
Password varchar(500) NOT NULL,
FirstName nvarchar(100) NOT NULL,
LastName nvarchar(100) NOT NULL
)

CREATE TABLE [Certificates](
Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY NOT NULL,
Name nvarchar(150) NOT NULL,
Organization nvarchar(100) NOT NULL,
IssueDate date NOT NULL,
ExpirationDate date
)

CREATE TABLE Educations(
Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY NOT NULL,
Institute nvarchar(100) NOT NULL,
Degree nvarchar(100) NOT NULL,
FieldOfStudy nvarchar(100) NOT NULL,
StartDate date NOT NULL,
EndDate date NOT NULL,
)

CREATE TABLE PersonalInfos(
Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY NOT NULL,
Address nvarchar(200) NOT NULL,
Phone varchar(15) NOT NULL,
UserId UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
FOREIGN KEY (UserId) REFERENCES Users(Id)
)

CREATE TABLE WorkExperiences(
Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY NOT NULL,
Company nvarchar(100) NOT NULL,
Position nvarchar(100) NOT NULL,
StartDate date NOT NULL,
EndDate date NOT NULL,
Description nvarchar(500) NOT NULL,
)

CREATE TABLE Templates(
Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY NOT NULL,
Name varchar(50) NOT NULL,
Path nvarchar(200) NOT NULL
)

CREATE TABLE Languages(
    Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY NOT NULL,
    Name nvarchar(100) NOT NULL,
    Proficiency tinyint NOT NULL,
)